version: '3'
services:
  feedit-web:
    image: feedit-server
    container_name: feedit-web
    ports:
      - "8080:6380"
    environment:
      SPRING_PROFILES_ACTIVE: production
  feedit-database:
    image: postgres:12.0
    container_name: feedit-database-prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: feedit
      POSTGRES_USER: feedit
      POSTGRES_PASSWORD: password
